var V=Object.defineProperty;var X=(e,t,s)=>t in e?V(e,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):e[t]=s;var d=(e,t,s)=>(X(e,typeof t!="symbol"?t+"":t,s),s),q=(e,t,s)=>{if(!t.has(e))throw TypeError("Cannot "+s)};var r=(e,t,s)=>(q(e,t,"read from private field"),s?s.call(e):t.get(e)),l=(e,t,s)=>{if(t.has(e))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(e):t.set(e,s)},S=(e,t,s,n)=>(q(e,t,"write to private field"),n?n.call(e,s):t.set(e,s),s);var C=(e,t,s)=>(q(e,t,"access private method"),s);import{D as B,B as M,e as F,c as g,b as U,v as z,m as N,a as K,d as Z,s as tt,i as et}from"./assets/handle-menu-buttons-e47ffd76.js";import"./assets/vendor-32231325.js";const st="Muscles",O="filters",H="exercises",nt=e=>{let t=8;const s=window.innerWidth;if(s>=1440)t=12;else if(s>=768)switch(e){case O:t=12;break;case H:t=6;break;default:t=8;break}return t},G=(e,t={},s=1,n="")=>{let i={};return t&&(i={...t}),e===H&&n&&(i={...i,keyword:n}),i={...i,page:s,limit:nt(O)},`${e}?${new URLSearchParams(i).toString()}`};async function it(e,t){const s=new B(M),n=G("filters",e,t);try{return await s.objectGetRequest(n)}catch{}}function rt(e=[]){return e.reduce((t,{imgUrl:s,name:n,filter:i})=>t+`
      <li class="filter-card" data-filter">
          <img src="${s}" alt="Image of: ${i}"/>
          <div class="filter-label">
          <p class="filter-name">${n}</p>
          <p class="filter-type">${i}</p>            
          </div>
      </li>
      `,"")}function D(e,t){return`<div class="rating-container">
                <p class="ex-card-rating">${e}</p>
                <svg
                  class="rating-star-icon"
                  width="18"
                  height="18"
                  aria-label="star icon"
                  fill = "#EEA10C";
                >
                  <use href="${t}#icon-star"></use>
                </svg>
              </div>`}const P=(e,t,s)=>{t.textContent="",t.classList.add("visually-hidden");let n="";e.length,n=s(e,D),n=s(e,D),t.innerHTML="",t.insertAdjacentHTML("beforeend",n),t.classList.remove("visually-hidden")},ot=(e,t)=>P(t,e,rt);async function _(e={},t=1,s=""){const n=new B(M),i=G(H,e,t,s);try{return await n.objectGetRequest(i)}catch{}}const at=(e,t)=>P(t,e,F);var o,v,h,u,w,W,L,T;class ct{constructor({galleryHandle:t,filter:s,dotsSelector:n,dotDefaultClass:i,dotActiveClass:c}){l(this,w);l(this,L);d(this,"currentPage",1);d(this,"totalPages",0);l(this,o,void 0);l(this,v,10);l(this,h,"pagination-dot");l(this,u,"active-paggination-dot");d(this,"galleryHandle");d(this,"filter",{filter:""});d(this,"keyWord","");this.galleryHandle=t,this.filter=s,S(this,u,c),S(this,h,i),S(this,o,document.querySelector(n)),r(this,o).addEventListener("click",this.onDotsClick.bind(this))}init(t,s,n=0){this.galleryHandle=t,this.totalPages=n>r(this,v)?r(this,v):n,this.filter=s,C(this,w,W).call(this)}reset(t,s,n=1,i="",c=0){this.galleryHandle=t,this.totalPages=c,this.currentPage=n,this.filter=s,this.keyWord=i,C(this,L,T).call(this)}destroy(){r(this,o).removeEventListener("click",this.onDotsClick.bind(this)),C(this,L,T).call(this)}async updateGallery(){try{await this.galleryHandle(this.filter,this.currentPage,this.keyWord,this.totalPages)}catch(t){console.log(t.message)}}onDotsClick(t){const s=t.target;if(!s.classList.contains(r(this,h)))return;const n=parseInt(s.dataset.ind,10);this.currentPage=n,this.updateDisplayDots(),this.updateGallery()}updateDisplayDots(){const t=r(this,o).querySelectorAll("li");t.forEach(s=>{s.classList.remove(r(this,u))}),t[this.currentPage-1].classList.add(r(this,u))}}o=new WeakMap,v=new WeakMap,h=new WeakMap,u=new WeakMap,w=new WeakSet,W=function(){r(this,o).innerHTML="";let t="";for(let s=0;s<this.totalPages;s+=1)t+=`
       <li class="${r(this,h)}" data-ind="${s+1}">${s+1}</li>
      `;r(this,o).innerHTML=t,r(this,o).children[this.currentPage-1].classList.add(r(this,u))},L=new WeakSet,T=function(){r(this,o).innerHTML=""};const j=e=>{e.innerHTML="",e.classList.add("visually-hidden")};function lt(){return`<p class="ex-no-elements">
              Unfortunately,  <span class="grey-text"> no results</span> were
              found. You may want to consider other search options to find the
              exercise you are looking for. Our range is wide and you have the
              opportunity to find more options that suit your needs.
          </p>`}const A="filter-button-active";let f={};const E=document.querySelector(".exercise-filter-title"),Y=document.querySelector(".filters-buttons"),R=document.querySelector(".exercise-filters-list"),x=document.querySelector(".exercises-gallery"),I=document.querySelector(".form-for-searching-input"),ut=document.querySelector(".searching-input");Y.addEventListener("click",dt);R.addEventListener("click",ft);I.addEventListener("submit",pt);const a=new ct({galleryHandle:y,dotsSelector:".pagination-dots",dotDefaultClass:"pagination-dot",dotActiveClass:"active-pagination-dot"});function dt(e){if(e.target.tagName!=="BUTTON")return;e.preventDefault();const t=e.target.dataset.filter;I.classList.add("visually-hidden"),a.reset(y,t,1,0),Lt(),y({filter:t}),gt(e.target)}function y(e={filter:st}){it(e,a.currentPage).then(t=>{const s=t.results;j(x),ot(R,s);const n=t.totalPages?t.totalPages:0;a.init(y,e,n)}).catch(t=>{console.log(t.message)})}function ft(e){e.preventDefault(),e.target;const t=e.target.closest("li");if(!t)return;const s={},n=t.querySelector(".filter-name"),i=t.querySelector(".filter-type");if(I.classList.remove("visually-hidden"),i&&i){const c=n.textContent.toLowerCase(),$=i.textContent.toLowerCase();if($==="")return;s[$]=c}St(n.textContent),a.reset(m,s,1,0),m(s)}function m(e){_(e,a.currentPage).then(t=>{j(R),at(x,t.results);const s=t.totalPages?t.totalPages:0;a.init(m,e,s)}).catch(t=>{console.log(t.message),g(`Error fetching images: ${t.message}`)})}function ht(){f=Y.querySelector("BUTTON"),f&&f.classList.add(A)}function gt(e){f&&f.classList.remove(A),e&&e.classList.add(A),f=e}function yt(){const e=document.querySelector(".filter-button-active"),t=document.querySelector(".chapter-text"),s={};return s[e.dataset.filter.toLowerCase()]=t.textContent.toLowerCase(),s}function mt(){return ut.value.trim().toLowerCase()}function pt(e){e.preventDefault();const t=mt();if(t===""){U("Please fill in the search field");return}const s=yt();a.reset(m,s,1,t,0),vt(s,t)}function vt(e,t){_(e,a.currentPage,t).then(s=>{s.results.length===0?P([],x,lt):P(s.results,x,F);const n=s.totalPages?s.totalPages:0;a.init(m,e,n)}).catch(s=>{console.log(s.message)})}function Lt(){E.textContent.indexOf("/")!==-1&&(E.textContent=E.textContent.split("/")[0])}function St(e){const t=` / 
  <span class="chapter-text">${e}</span>`;E.insertAdjacentHTML("beforeend",t)}ht();y();const Ct="We're excited to have you on board! 🎉 Thank you for subscribing to new exercises on Energy Flow. You've just taken a significant step towards improving your fitness and well-being.",Et="Subscription already exists",Pt="Please, enter a valid email address",xt="Sorry! Something is wrong",p=document.querySelector(".footer-subscription"),b=p.querySelector(".input-footer"),bt=document.querySelector(".footer-button");p&&p.addEventListener("submit",kt);b&&b.addEventListener("input",k);function kt(e){e.preventDefault();const t=b.value.trim();if(!t){g(NO_EMAIL);return}if(!z(t)){g(Pt),p.reset(),k();return}const s={method:"POST",body:JSON.stringify({email:t}),headers:{"Content-Type":"application/json"}};fetch(`${M}subscription`,s).then(n=>{n.status>=200&&n.status<300&&U(Ct),n.status===409&&g(Et)}).catch(n=>{console.log(n),g(xt)}).finally(()=>{p.reset(),k()})}function k(e){bt.disabled=!b.value.trim()}k();const Q=document.querySelectorAll(".button-home"),J=document.querySelectorAll(".button-favorites");N(Q,J);J.forEach(e=>{e.addEventListener("click",t=>{N([e],Q)})});K();const wt={iconURL:et,iconContainerClass:"social-item-footer",iconLinkClass:"social-link-footer",iconClass:"social-icon"},qt=document.querySelector(".social-list");Z(qt,wt,tt);
//# sourceMappingURL=commonHelpers2.js.map
