var Q=Object.defineProperty;var z=(e,t,s)=>t in e?Q(e,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):e[t]=s;var d=(e,t,s)=>(z(e,typeof t!="symbol"?t+"":t,s),s),b=(e,t,s)=>{if(!t.has(e))throw TypeError("Cannot "+s)};var r=(e,t,s)=>(b(e,t,"read from private field"),s?s.call(e):t.get(e)),l=(e,t,s)=>{if(t.has(e))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(e):t.set(e,s)},L=(e,t,s,i)=>(b(e,t,"write to private field"),i?i.call(e,s):t.set(e,s),s);var P=(e,t,s)=>(b(e,t,"access private method"),s);import{D as $,B as I,e as F,c as g,b as R,m as U,a as J,d as V,s as X,i as Z}from"./assets/handle-menu-buttons-5cc0534b.js";import"./assets/vendor-32231325.js";const K="Muscles",B="filters",T="exercises",tt=e=>{let t=8;const s=window.innerWidth;if(s>=1440)t=12;else if(s>=768)switch(e){case B:t=12;break;case T:t=6;break;default:t=8;break}return t},N=(e,t={},s=1,i="")=>{let n={};return t&&(n={...t}),e===T&&i&&(n={...n,keyword:i}),n={...n,page:s,limit:tt(B)},`${e}?${new URLSearchParams(n).toString()}`};async function et(e,t){const s=new $(I),i=N("filters",e,t);try{return await s.objectGetRequest(i)}catch{}}function st(e=[]){return e.reduce((t,{imgUrl:s,name:i,filter:n})=>t+`
      <li class="filter-card" data-filter">
          <img src="${s}" alt="Image of: ${n}"/>
          <div class="filter-label">
          <p class="filter-name">${i}</p>
          <p class="filter-type">${n}</p>            
          </div>
      </li>
      `,"")}function k(e,t){return`<div class="rating-container">
                <p class="ex-card-rating">${e}</p>
                <svg
                  class="rating-star-icon"
                  width="18"
                  height="18"
                  aria-label="star icon"
                  fill = "#EEA10C";
                >
                  <use href="${t}#icon-star"></use>
                </svg>
              </div>`}const S=(e,t,s)=>{t.textContent="",t.classList.add("visually-hidden");let i="";e.length,i=s(e,k),i=s(e,k),t.innerHTML="",t.insertAdjacentHTML("beforeend",i),t.classList.remove("visually-hidden")},it=(e,t)=>S(t,e,st);async function O(e={},t=1,s=""){const i=new $(I),n=N(T,e,t,s);try{return await i.objectGetRequest(n)}catch{}}const nt=(e,t)=>S(t,e,F);var o,m,h,u,E,j,v,q;class rt{constructor({galleryHandle:t,filter:s,dotsSelector:i,dotDefaultClass:n,dotActiveClass:c}){l(this,E);l(this,v);d(this,"currentPage",1);d(this,"totalPages",0);l(this,o,void 0);l(this,m,10);l(this,h,"pagination-dot");l(this,u,"active-paggination-dot");d(this,"galleryHandle");d(this,"filter",{filter:""});d(this,"keyWord","");this.galleryHandle=t,this.filter=s,L(this,u,c),L(this,h,n),L(this,o,document.querySelector(i)),r(this,o).addEventListener("click",this.onDotsClick.bind(this))}init(t,s,i=0){this.galleryHandle=t,this.totalPages=i>r(this,m)?r(this,m):i,this.filter=s,P(this,E,j).call(this)}reset(t,s,i=1,n="",c=0){this.galleryHandle=t,this.totalPages=c,this.currentPage=i,this.filter=s,this.keyWord=n,P(this,v,q).call(this)}destroy(){r(this,o).removeEventListener("click",this.onDotsClick.bind(this)),P(this,v,q).call(this)}async updateGallery(){try{await this.galleryHandle(this.filter,this.currentPage,this.keyWord,this.totalPages)}catch(t){console.log(t.message)}}onDotsClick(t){const s=t.target;if(!s.classList.contains(r(this,h)))return;const i=parseInt(s.dataset.ind,10);this.currentPage=i,this.updateDisplayDots(),this.updateGallery()}updateDisplayDots(){const t=r(this,o).querySelectorAll("li");t.forEach(s=>{s.classList.remove(r(this,u))}),t[this.currentPage-1].classList.add(r(this,u))}}o=new WeakMap,m=new WeakMap,h=new WeakMap,u=new WeakMap,E=new WeakSet,j=function(){r(this,o).innerHTML="";let t="";for(let s=0;s<this.totalPages;s+=1)t+=`
       <li class="${r(this,h)}" data-ind="${s+1}">${s+1}</li>
      `;r(this,o).innerHTML=t,r(this,o).children[this.currentPage-1].classList.add(r(this,u))},v=new WeakSet,q=function(){r(this,o).innerHTML=""};const G=e=>{e.innerHTML="",e.classList.add("visually-hidden")};function ot(){return`<p class="ex-no-elements">
              Unfortunately,  <span class="grey-text"> no results</span> were
              found. You may want to consider other search options to find the
              exercise you are looking for. Our range is wide and you have the
              opportunity to find more options that suit your needs.
          </p>`}const D="filter-button-active";let f={};const C=document.querySelector(".exercise-filter-title"),W=document.querySelector(".filters-buttons"),A=document.querySelector(".exercise-filters-list"),w=document.querySelector(".exercises-gallery"),H=document.querySelector(".form-for-searching-input"),at=document.querySelector(".searching-input");W.addEventListener("click",ct);A.addEventListener("click",lt);H.addEventListener("submit",gt);const a=new rt({galleryHandle:y,dotsSelector:".pagination-dots",dotDefaultClass:"pagination-dot",dotActiveClass:"active-pagination-dot"});function ct(e){if(e.target.tagName!=="BUTTON")return;e.preventDefault();const t=e.target.dataset.filter;H.classList.add("visually-hidden"),a.reset(y,t,1,0),pt(),y({filter:t}),dt(e.target)}function y(e={filter:K}){et(e,a.currentPage).then(t=>{const s=t.results;G(w),it(A,s);const i=t.totalPages?t.totalPages:0;a.init(y,e,i)}).catch(t=>{console.log(t.message)})}function lt(e){e.preventDefault(),e.target;const t=e.target.closest("li");if(!t)return;const s={},i=t.querySelector(".filter-name"),n=t.querySelector(".filter-type");if(H.classList.remove("visually-hidden"),n&&n){const c=i.textContent.toLowerCase(),M=n.textContent.toLowerCase();if(M==="")return;s[M]=c}mt(i.textContent),a.reset(p,s,1,0),p(s)}function p(e){O(e,a.currentPage).then(t=>{G(A),nt(w,t.results);const s=t.totalPages?t.totalPages:0;a.init(p,e,s)}).catch(t=>{console.log(t.message),g(`Error fetching images: ${t.message}`)})}function ut(){f=W.querySelector("BUTTON"),f&&f.classList.add(D)}function dt(e){f&&f.classList.remove(D),e&&e.classList.add(D),f=e}function ft(){const e=document.querySelector(".filter-button-active"),t=document.querySelector(".chapter-text"),s={};return s[e.dataset.filter.toLowerCase()]=t.textContent.toLowerCase(),s}function ht(){return at.value.trim().toLowerCase()}function gt(e){e.preventDefault();const t=ht();if(t===""){R("Please fill in the search field");return}const s=ft();a.reset(p,s,1,t,0),yt(s,t)}function yt(e,t){O(e,a.currentPage,t).then(s=>{s.results.length===0?S([],w,ot):S(s.results,w,F);const i=s.totalPages?s.totalPages:0;a.init(p,e,i)}).catch(s=>{console.log(s.message)})}function pt(){C.textContent.indexOf("/")!==-1&&(C.textContent=C.textContent.split("/")[0])}function mt(e){const t=` / 
  <span class="chapter-text">${e}</span>`;C.insertAdjacentHTML("beforeend",t)}ut();y();const x=document.querySelector(".footer-subscription"),vt=x.querySelector(".input-footer");x.addEventListener("submit",Lt);function Lt(e){e.preventDefault();const t=/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/,s=vt.value.trim();if(!s){g("Please enter email");return}if(!t.test(s)){g("Please enter a valid email"),x.reset();return}const i={method:"POST",body:JSON.stringify({email:s}),headers:{"Content-Type":"application/json"}};fetch("https://energyflow.b.goit.study/api/subscription",i).then(n=>{n.status>=200&&n.status<300&&R("We're excited to have you on board! 🎉 Thank you for subscribing to new exercises on Energy Flow. You've just taken a significant step towards improving your fitness and well-being."),n.status===409&&g("Subscription already exists")}).catch(n=>{console.log(n),g("Sorry! Something is wrong")}).finally(()=>{x.reset()})}const Y=document.querySelectorAll(".button-home"),_=document.querySelectorAll(".button-favorites");U(Y,_);_.forEach(e=>{e.addEventListener("click",t=>{U([e],Y)})});J();const Pt={iconURL:Z,iconContainerClass:"social-item-footer",iconLinkClass:"social-link-footer",iconClass:"social-icon"},Ct=document.querySelector(".social-list");V(Ct,Pt,X);
//# sourceMappingURL=commonHelpers2.js.map
